# Generated by Django 5.2.6 on 2025-10-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accountuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
