# Generated by Django 5.2.6 on 2025-10-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_conversation_alter_chat_reciever_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='reciever',
        ),
    ]
