# Generated by Django 5.2.6 on 2025-10-23 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accountuser_managers_alter_accountuser_email'),
        ('chats', '0003_remove_chat_reciever'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ended', 'Ended'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='initiated', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to='accounts.profile')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='chats.conversation')),
                ('participants', models.ManyToManyField(related_name='received_calls', to='accounts.profile')),
            ],
            options={
                'permissions': [('View_Calls', 'Can View Calls'), ('Edit_Calls', 'Can Edit Calls'), ('Delete_Calls', 'Can Delete Calls')],
            },
        ),
    ]
